version: '3'
services:
  mongo:
    image: mongo:4.4.6
    volumes:
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - 27017:27017
  minio:
    image: minio/minio
    volumes:
      - data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: xExFnjfGq7tN
      MINIO_SECRET_KEY: dBXJphBwkaaM
    command: server /data
volumes:
  data:
